# Generated by Django 5.2.8 on 2026-02-06 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DisciplineCommittee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="category",
        ),
        migrations.RemoveField(
            model_name="case",
            name="remarks",
        ),
        migrations.AddField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("Late Arrival", "Late Arrival"),
                    ("Academic Misconduct", "Academic Misconduct"),
                    ("Uniform Violation", "Uniform Violation"),
                    ("Other", "Other"),
                ],
                default="Late Arrival",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="case",
            name="date",
            field=models.DateField(),
        ),
    ]
