# Generated by Django 5.2.8 on 2026-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DisciplineCommittee",
            "0002_remove_case_category_remove_case_remarks_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("Late Arrival", "Late Arrival"),
                    ("Uniform Violation", "Uniform Violation"),
                    ("Academic Misconduct", "Academic Misconduct"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
