# Generated by Django 5.2.8 on 2026-02-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DisciplineCommittee", "0003_alter_case_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("Late Arrival", "Late Arrival"),
                    ("Academic Misconduct", "Academic Misconduct"),
                    ("Uniform Violation", "Uniform Violation"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
