# Generated by Django 5.2.8 on 2026-02-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DisciplineCommittee", "0004_alter_case_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
