# Generated by Django 5.2.8 on 2026-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DisciplineCommittee", "0005_alter_case_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniformViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usn", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("prior_count", models.IntegerField()),
                ("violations", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
